### PR TITLE
Added side-by-side diff and other enhancements

### PR DESCRIPTION
**Pull request by induane**
New Features:
- Side-by-side diff option added
- Converted to a setuptools/distutils style project so packages can easily be made and distributed
- Fixed some minor bugs and improved the code style
- Improved command line options:
  - Added flag for accurate mode
  - Added flag for producing a side-by-side diff
- Added entry point to setup.py file so when installed as a package the "diff_html" tool is available
  on the path.

### CODE REVIEW

**Comment by induane** [comment]
I'd almost completely lost track of this thread, I actually kind of like htmldelta but I'm fine with htmldiff in the end :)

**Comment by cygri** [comment]
Ah, thanks for picking this up again! Looks like the README still refers to diff_html in a few places, should that be changed to htmldiff?

**Comment by induane** [comment]
Yep I probably just missed that. I'll update it when I get in to the office
today. Cheers!

**Comment by induane** [comment]
I updated it to use Argparse while I'm at it since Optparse is pretty well deprecated at this point. I don't think I missed anything, but let me know if I did.

**Comment by induane** [comment]
Commit summary since the multi-year haitus: 

## Update entrypoint name
- Entrypoint name changed to "htmldiff"
## Convert to Argparse
- Use Argparse instead of deprecated OptParse
- Attempt to better handle files that come in utf8 encoded
- Update readme with appropriate entrypoint name
- Added -V version option

## Split tooling into lib, cleanups
- Command-line entry points now are in own module
- Use logging system for user messages
- Added -l (log level) and -L logfile options for output
- Removed all print statements
- When errors cause an early exit, don't exit with an error code of 0
- Made code-style more consistent
  - lowercase snake_case for function names
  - CamelCase for class names
- Use a precompiled regex for split search
- Use a frozenset for stopwords (membership checking in a frozenset is very fast)

## Write either to stdout or to a file
- Updated readme
- now writes to stdout if no output file given, which means it can be used within bash pipelines (user output is logged so not written to stdout)

**Comment by cygri** [comment]
Fantastic work!

The ball is now in my court to do a bit of testing and merge the PR. That's now on my to-do list. Feel free to remind me if you feel it takes too long.

Or are there any lurkers willing to test-drive @induane's changes and give a +1?

**Comment by cygri** [comment]
So I tested this on the content of these two URLs:
https://www.w3.org/TR/2016/WD-shacl-20160814/
https://www.w3.org/TR/2017/WD-shacl-20170202/

These are two versions of the same document, with lots of changes, but also significant parts that remained the same.

The current htmldiff does a very poor job at handling markup and the like, but is doing reasonably well with the content: some sections are red, some are green, some are white.

The updated htmldiff from this PR does a much better job at keeping the markup intact, but it doesn't handle the content properly. Almost all of the document appears as green with strike-through, which I guess indicates that almost all content is seen as both added *and* deleted. The `-a` flag doesn't seem to make much of a difference to the result, and `-s` didn't work at all here but that might be due to the fancy markup.

Am I wrong to expect a result closer to the old behaviour here?

**Comment by induane** [comment]
@cygri not to my knowledge you're not wrong. I don't *remember* changing anything in terms of functionality in that way as it was more of an extension.

Of course the results speak for themselves so - it's incumbent upon me to see wtf I did wrong :)

**Comment by cygri** [comment]
This is giving me good results on some test documents.

Would you mind doing one last change on this PR? Edit the beginning of README.md to highlight your own significant contributions to this version?

Then I'm ready to hit the big green button.

**Comment by cygri** [comment]
After three and a half years! 🎉

Thanks for the great work on this, induane.

**Pull request merged**
